# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        ANONYMIZATION_SALT: ${{ secrets.ANONYMIZATION_SALT }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        BASE_URL: ${{ secrets.BASE_URL }}
        GSUITE_CLIENT_EMAIL: ${{ secrets.GSUITE_CLIENT_EMAIL }}
        GSUITE_PRIVATE_KEY: ${{ secrets.GSUITE_PRIVATE_KEY }}
        GSUITE_SCOPES: ${{ secrets.GSUITE_SCOPES }}
        GSUITE_TEST_USER: ${{ secrets.GSUITE_TEST_USER }}
        INTERNAL_DOMAIN_LIST: ${{ secrets.INTERNAL_DOMAIN_LIST }}
        VERBOSITY: ${{ secrets.VERBOSITY }}
